package Game3072Project;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import javax.swing.JButton;
import javax.swing.JFrame;
import java.io.File; 
import java.io.FileNotFoundException; 
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Scanner;
import javax.swing.BorderFactory;
import javax.swing.JTextArea;

/**
 * This GUI form creates the game page and grid of buttons. It also keeps track
 * of current score and high score.
 * The opening and running of this pages is handled in the MainProgram and
 * the other two JFrames.
 */
public class GamePages extends javax.swing.JFrame {
    
    HomePage hp;
    public void setHomePage(HomePage home){hp = home;}
    public HomePage getHomePage(){return hp;}
            
    Board board;
    public void setBoard(Board newBoard){board = newBoard;}
    public Board getBoard(){return board;}
    
    //Create colors;
    public static final Color BackgroundColor = new Color(182,215,168);
    public static final Color normalBackground = new Color(183,183,183);
    public static final Color Color3    = new Color(182,215,168);
    public static final Color Color6    = new Color(147,196,125);
    public static final Color Color12   = new Color(106,168,79);
    public static final Color Color24   = new Color(65,137,35);
    public static final Color Color48   = new Color(49,97,25);
    public static final Color Color96   = new Color(255,223,239);
    public static final Color Color192  = new Color(255,177,216);
    public static final Color Color384  = new Color(254,152,203);
    public static final Color Color768  = new Color(250,85,169);
    public static final Color Color1536 = new Color(254,49,152);
    public static final Color Color3072 = new Color(250,0,127);


    /**
     * Creates new form GamePage
     */
    public GamePages() {
        
        initComponents();
        JButton[][] buttonArray = {
            {Button1,Button2,Button3,Button4},
            {Button5,Button6,Button7,Button8},
            {Button9,Button10,Button11,Button12},
            {Button13,Button14,Button15,Button16}
        };
        
        board = new Board(buttonArray);
        board.setGamePage(this);
        
        //Makes the background the green color;
        this.getContentPane().setBackground(BackgroundColor);
        
       
        
        board.generateTwoTiles();
        ScoreAmount.setText("0");
        getHighScore();
        
        
        this.setFocusable(true);      

        this.addKeyListener(new KeyListener() {
            @Override
            public void keyPressed(KeyEvent e) {
                int keyCode = e.getKeyCode();
                switch (keyCode) {
                    case KeyEvent.VK_UP, KeyEvent.VK_W:
                        // Handle up arrow key press
                        board.move(Board.UP);
                        break;
                    case KeyEvent.VK_RIGHT, KeyEvent.VK_D:
                        // Handle right arrow key press
                        board.move(Board.RIGHT);
                        break;
                    case KeyEvent.VK_DOWN, KeyEvent.VK_S:
                        // Handle down arrow key press
                        board.move(Board.DOWN);
                        break;
                    case KeyEvent.VK_LEFT, KeyEvent.VK_A:
                        // Handle left arrow key press
                        board.move(Board.LEFT);
                        break;
                    default:
                        // Ignore other key presses
                        break;
                }
            }

            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }

            });
        
        
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BestFrame2 = new javax.swing.JPanel();
        BestAmount2 = new javax.swing.JLabel();
        BestLabel2 = new javax.swing.JLabel();
        HomeButton = new javax.swing.JButton();
        ScoreFrame = new javax.swing.JPanel();
        ScoreAmount = new javax.swing.JLabel();
        ScoreLabel = new javax.swing.JLabel();
        NewGameButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Button3 = new javax.swing.JButton();
        Button16 = new javax.swing.JButton();
        Button14 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button10 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button13 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button12 = new javax.swing.JButton();
        Button15 = new javax.swing.JButton();
        Button11 = new javax.swing.JButton();
        InstructionsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BestFrame2.setBackground(new java.awt.Color(81, 120, 39));
        BestFrame2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BestFrame2.setFocusable(false);

        BestAmount2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BestAmount2.setForeground(new java.awt.Color(0, 0, 0));
        BestAmount2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BestAmount2.setText("3072");

        BestLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BestLabel2.setForeground(new java.awt.Color(0, 0, 0));
        BestLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BestLabel2.setText("Best");

        javax.swing.GroupLayout BestFrame2Layout = new javax.swing.GroupLayout(BestFrame2);
        BestFrame2.setLayout(BestFrame2Layout);
        BestFrame2Layout.setHorizontalGroup(
            BestFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BestFrame2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(BestLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(BestAmount2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BestFrame2Layout.setVerticalGroup(
            BestFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BestFrame2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(BestLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BestAmount2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        HomeButton.setBackground(new java.awt.Color(247, 135, 192));
        HomeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HomeButton.setForeground(new java.awt.Color(0, 0, 0));
        HomeButton.setText("Home");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        ScoreFrame.setBackground(new java.awt.Color(255, 177, 216));
        ScoreFrame.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ScoreFrame.setFocusable(false);

        ScoreAmount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ScoreAmount.setForeground(new java.awt.Color(0, 0, 0));
        ScoreAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScoreAmount.setText("192");

        ScoreLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ScoreLabel.setForeground(new java.awt.Color(0, 0, 0));
        ScoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScoreLabel.setText("Score");

        javax.swing.GroupLayout ScoreFrameLayout = new javax.swing.GroupLayout(ScoreFrame);
        ScoreFrame.setLayout(ScoreFrameLayout);
        ScoreFrameLayout.setHorizontalGroup(
            ScoreFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScoreFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ScoreFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ScoreFrameLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(ScoreLabel)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(ScoreAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ScoreFrameLayout.setVerticalGroup(
            ScoreFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScoreFrameLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScoreAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NewGameButton.setBackground(new java.awt.Color(247, 135, 192));
        NewGameButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NewGameButton.setForeground(new java.awt.Color(0, 0, 0));
        NewGameButton.setText("New Game");
        NewGameButton.setFocusPainted(false);
        NewGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameButtonActionPerformed(evt);
            }
        });
        NewGameButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NewGameButtonKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(116, 116, 116));

        Button3.setBackground(new java.awt.Color(183, 183, 183));
        Button3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Button3.setForeground(new java.awt.Color(0, 0, 0));
        Button3.setFocusable(false);
        Button3.setRolloverEnabled(false);
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        Button16.setBackground(new java.awt.Color(183, 183, 183));
        Button16.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Button16.setForeground(new java.awt.Color(0, 0, 0));
        Button16.setFocusable(false);
        Button16.setRolloverEnabled(false);
        Button16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button16ActionPerformed(evt);
            }
        });

        Button14.setBackground(new java.awt.Color(183, 183, 183));
        Button14.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Button14.setForeground(new java.awt.Color(0, 0, 0));
        Button14.setFocusable(false);
        Button14.setRolloverEnabled(false);
        Button14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button14ActionPerformed(evt);
            }
        });

        Button6.setBackground(new java.awt.Color(183, 183, 183));
        Button6.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Button6.setForeground(new java.awt.Color(0, 0, 0));
        Button6.setFocusable(false);
        Button6.setRolloverEnabled(false);
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        Button10.setBackground(new java.awt.Color(183, 183, 183));
        Button10.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Button10.setForeground(new java.awt.Color(0, 0, 0));
        Button10.setFocusable(false);
        Button10.setRolloverEnabled(false);
        Button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button10ActionPerformed(evt);
            }
        });

        Button4.setBackground(new java.awt.Color(183, 183, 183));
        Button4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Button4.setForeground(new java.awt.Color(0, 0, 0));
        Button4.setFocusable(false);
        Button4.setRolloverEnabled(false);
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });

        Button7.setBackground(new java.awt.Color(183, 183, 183));
        Button7.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Button7.setForeground(new java.awt.Color(0, 0, 0));
        Button7.setFocusable(false);
        Button7.setRolloverEnabled(false);
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        Button5.setBackground(new java.awt.Color(183, 183, 183));
        Button5.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Button5.setForeground(new java.awt.Color(0, 0, 0));
        Button5.setFocusable(false);
        Button5.setRolloverEnabled(false);
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        Button8.setBackground(new java.awt.Color(183, 183, 183));
        Button8.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Button8.setForeground(new java.awt.Color(0, 0, 0));
        Button8.setFocusable(false);
        Button8.setRolloverEnabled(false);
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button13.setBackground(new java.awt.Color(183, 183, 183));
        Button13.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Button13.setForeground(new java.awt.Color(0, 0, 0));
        Button13.setFocusable(false);
        Button13.setRolloverEnabled(false);
        Button13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button13ActionPerformed(evt);
            }
        });

        Button2.setBackground(new java.awt.Color(183, 183, 183));
        Button2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Button2.setForeground(new java.awt.Color(0, 0, 0));
        Button2.setFocusable(false);
        Button2.setRolloverEnabled(false);
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        Button9.setBackground(new java.awt.Color(183, 183, 183));
        Button9.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Button9.setForeground(new java.awt.Color(0, 0, 0));
        Button9.setFocusable(false);
        Button9.setRolloverEnabled(false);
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });

        Button1.setBackground(new java.awt.Color(183, 183, 183));
        Button1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Button1.setForeground(new java.awt.Color(0, 0, 0));
        Button1.setFocusable(false);
        Button1.setRolloverEnabled(false);
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Button12.setBackground(new java.awt.Color(183, 183, 183));
        Button12.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Button12.setForeground(new java.awt.Color(0, 0, 0));
        Button12.setFocusable(false);
        Button12.setRolloverEnabled(false);
        Button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button12ActionPerformed(evt);
            }
        });

        Button15.setBackground(new java.awt.Color(183, 183, 183));
        Button15.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Button15.setForeground(new java.awt.Color(0, 0, 0));
        Button15.setFocusable(false);
        Button15.setRolloverEnabled(false);
        Button15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button15ActionPerformed(evt);
            }
        });

        Button11.setBackground(new java.awt.Color(183, 183, 183));
        Button11.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Button11.setForeground(new java.awt.Color(0, 0, 0));
        Button11.setFocusable(false);
        Button11.setRolloverEnabled(false);
        Button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Button13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Button10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(Button11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Button14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(Button3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(Button4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(Button1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(Button6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(Button7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(Button8, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Button10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(Button11, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(Button12, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button13, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(Button14, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(Button15, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(Button16, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        InstructionsButton.setBackground(new java.awt.Color(247, 135, 192));
        InstructionsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        InstructionsButton.setForeground(new java.awt.Color(0, 0, 0));
        InstructionsButton.setText("Instructions");
        InstructionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructionsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(ScoreFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BestFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NewGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InstructionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NewGameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoreFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(BestFrame2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InstructionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGameButtonActionPerformed
        //ADD reset score
        ScoreAmount.setText(Integer.toString(0));
        board.setScore(0);
        
        board.setNumberArray(new int[4][4]); //wipes the array
        board.generateTwoTiles(); //new tiles.
        for(int ii=0;ii<4;ii++){
            for(int jj = 0; jj<4; jj++){
                board.updateColor(ii, jj);
                
                
            }
        }
        this.setFocusable(true);
        this.requestFocus();
        
    }//GEN-LAST:event_NewGameButtonActionPerformed

    private void NewGameButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NewGameButtonKeyPressed

    }//GEN-LAST:event_NewGameButtonKeyPressed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button16ActionPerformed

    private void Button14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button14ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button10ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button13ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button9ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        
    //BestWinMethod();
        
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button12ActionPerformed

    private void Button15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button15ActionPerformed

    private void Button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button11ActionPerformed

    /**
     * Opens or shows a home page and hides this current page
     */
    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        //make sure there's only one instance of each
        if(hp == null){
            hp = new HomePage();
        }
        hp.setGamePage(this);
         //set new JFrame to visible and hide this one
        hp.setVisible(true);
        hp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
        
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void InstructionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructionsButtonActionPerformed
        Color textColor = Color.black;

        JFrame instructionsFrame = new JFrame("Instructions For 3072");
        instructionsFrame.setSize(500, 500);
        instructionsFrame.setVisible(true);
        instructionsFrame.getContentPane().setBackground(BackgroundColor);
        instructionsFrame.setLocationRelativeTo(null); //https://www.tutorialspoint.com/how-to-display-a-jframe-to-the-center-of-a-screen-in-java#:~:text=By%20default%2C%20a%20JFrame%20can,()%20method%20of%20Window%20class.

        
        JTextArea instructionsTextArea = new JTextArea();
        instructionsTextArea.setFocusable(false);
        instructionsTextArea.setOpaque(false);
        instructionsTextArea.setBounds(5, 5, 200, 250); 
        instructionsTextArea.setText("Instructions for 3072:\n\n1. Move the tiles with arrow keys\n2. Combine the same number tiles \n to create a higher number\n3. Reach 3072 to win the game!");
        instructionsTextArea.setFont(new Font("Arial", Font.BOLD, 30));  
        instructionsTextArea.setForeground(textColor);
        instructionsTextArea.setAlignmentX(Component.CENTER_ALIGNMENT);
        instructionsTextArea.setBorder(BorderFactory.createLineBorder(Color1536, 3)); // add a border
        instructionsFrame.add(instructionsTextArea);
        
        instructionsFrame.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                focus();
            }
        });
        
    }//GEN-LAST:event_InstructionsButtonActionPerformed

    public void updateScore(int score){
    ScoreAmount.setText("" + score);
    String filepath="";

    try { 
        String currentDir = System.getProperty("user.dir");
        filepath = currentDir + "\\src\\Game3072Project\\HighScore.txt";
    

        File file = new File(filepath);

        Scanner reader = new Scanner(file);
        while (reader.hasNextInt()) {
            int highScore1 = reader.nextInt();

            if(highScore1 < score){
                //update file
                BestAmount2.setText(""+ score);

                try{
                    FileWriter myWriter = new FileWriter(file.getPath());
                    PrintWriter pw = new PrintWriter(myWriter);
                    pw.println(score);
                    pw.close();
                    myWriter.close();
                }
                catch(IOException e){
                    //System.out.println("An error occured");
                    e.printStackTrace();
                }
            }
        }
        reader.close();
    } catch (FileNotFoundException e) {
        //System.out.println("An error occurred.");
        e.printStackTrace();
    }
}
    
    public void getHighScore(){
        
        String filepath="";
        
        try { 
        String currentDir = System.getProperty("user.dir");
        filepath = currentDir + "\\src\\Game3072Project\\HighScore.txt";
    

        File file = new File(filepath);

        Scanner reader = new Scanner(file);
        while (reader.hasNextInt()) {
            int highScore1 = reader.nextInt();
            BestAmount2.setText(Integer.toString(highScore1));
            }
        reader.close();
    } catch (FileNotFoundException e) {
        //System.out.println("An error occurred.");
        e.printStackTrace();
    }
        
    }
    
    public void gameOver(){
        Button5.setText("G");
        Button6.setText("A");
        Button7.setText("M");
        Button8.setText("E"); 
        Button9.setText("O");
        Button10.setText("V");
        Button11.setText("E");
        Button12.setText("R");
        
        Button5.setBackground(Color12);
        Button6.setBackground(Color12);
        Button7.setBackground(Color12);
        Button8.setBackground(Color12); 
        Button9.setBackground(Color12);
        Button10.setBackground(Color12);
        Button11.setBackground(Color12);
        Button12.setBackground(Color12);
        
        this.setFocusable(false);
    }
    
    public void win(){
        Button5.setText("Y");
        Button6.setText("O");
        Button7.setText("U");
        
        Button9.setText("W");
        Button10.setText("O");
        Button11.setText("N");
        Button12.setText("!");
        
        Button5.setBackground(Color192);
        Button6.setBackground(Color192);
        Button7.setBackground(Color192);
        
        Button9.setBackground(Color192);
        Button10.setBackground(Color192);
        Button11.setBackground(Color192);
        Button12.setBackground(Color192);
        this.setFocusable(false);
    }
    public void focus(){
        this.requestFocus();
    }
    
    public void BestWinMethod(){
        
        while(board.countOpenSpots()!=0){
        board.move(0);
        board.move(1);
        board.move(2);
        board.move(3);
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BestAmount2;
    private javax.swing.JPanel BestFrame2;
    private javax.swing.JLabel BestLabel2;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button10;
    private javax.swing.JButton Button11;
    private javax.swing.JButton Button12;
    private javax.swing.JButton Button13;
    private javax.swing.JButton Button14;
    private javax.swing.JButton Button15;
    private javax.swing.JButton Button16;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton InstructionsButton;
    private javax.swing.JButton NewGameButton;
    private javax.swing.JLabel ScoreAmount;
    private javax.swing.JPanel ScoreFrame;
    private javax.swing.JLabel ScoreLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
